# Copyright (C) 2011 Codership Oy <info@codership.com>

env = DefaultEnvironment()

conf = Configure(env)

boost_program_options = '/usr/lib/libboost_program_options.a'
if not conf.CheckLibWithHeader(libs=['boost_program_options'],
                               header='boost/program_options.hpp',
                               language='CXX',
                               autoadd=0):
    print 'Error: ' + boost_program_oprions + ' not found'
    Exit (1)

env.Append(LIBS=File('#/gcs/src/libgcs4garb.a'))
env.Append(LIBS=File('#/gcomm/src/libgcomm.a'))
env.Append(LIBS=File('#/galerautils/src/libgalerautils.a'))
env.Append(LIBS=File('#/galerautils/src/libgalerautils++.a'))
env.Append(LIBS=File(boost_program_options))

garb = env.Program(target = 'garbd',
                   source = Split('''
                                  garb_logger.cpp
                                  garb_config.cpp
                                  garb_gcs.cpp
                                  garb_recv_loop.cpp
                                  garb_main.cpp
                              ''')
                   )

