
Import('check_env')

env = check_env.Clone()

env.Prepend(LIBS = Split('''
                            wsdb
                            galerautils
                         '''))

wsdb_check = env.Program(target = 'check_wsdb',
                         source = Split('''
                              test_file.c
                              test_hash.c
                              test_cache.c
                              test_wsdb.c
                              test_version_file.c
                              test_xdr.c
                              test_log.c
                              test_mempool.c
                              wsdb_test.c
                           '''))

stamp = str(wsdb_check[0].path) + ".passed"
env.Test(stamp, wsdb_check)
env.Alias("test", stamp)

