.TH GARBD "8" "December 2014" "garbd  INFO: 2.8.r165" "System Administration Utilities"
.SH NAME
garbd \- The Galera Arbitrator daemon

.SH SYNOPSIS
.B garbd
[\fI\,options\/\fR] [\fI\,group address\/\fR]

.SH DESCRIPTION
.B garbd

This man page is a stub. Please contribute.

.SH PARAMETERS
.SS "Configuration:"
.TP
\fB\-d\fR [ \fB\-\-daemon\fR ]
Become daemon
.TP
\fB\-a\fR [ \fB\-\-address\fR ] arg
Group address
.TP
\fB\-g\fR [ \fB\-\-group\fR ] arg
Group name
.TP
\fB\-\-sst\fR arg
SST request string
.TP
\fB\-\-donor\fR arg
SST donor name
.TP
\fB\-o\fR [ \fB\-\-options\fR ] arg
GCS/GCOMM option list
.TP
\fB\-l\fR [ \fB\-\-log\fR ] arg
Log file
.TP
\fB\-c\fR [ \fB\-\-cfg\fR ] arg
Configuration file
.SS "Other options:"
.TP
\fB\-v\fR [ \fB\-\-version\fR ]
Print version
.TP
\fB\-h\fR [ \fB\-\-help\fR ]
Show help message
.PP

.SH "SEE ALSO"
Run garbd \-\-help to get the current list of parameters supported by the binary
