# 

env = DefaultEnvironment()

libgcomm_env = env.Clone()
libgcomm_env.Append(CXXFLAGS = ' -fno-strict-aliasing')
libgcomm_env.SharedLibrary('gcomm', Glob('*.cpp'))
libgcomm_env.StaticLibrary('gcomm', Glob('*.cpp'))
