language: cpp

sudo: false

cache:
  - apt
  - ccache

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
#     https://github.com/travis-ci/travis-ci/issues/3668
#     for alternatives in container builds
      - llvm-toolchain-precise-3.8
    packages:
      - libboost-program-options-dev
      - libssl-dev
      - check
      - scons
      - gcc-5
      - g++-5
      - clang-3.8

script:
  - if [ ${CC} != "clang" ]; then
      MEM=$(head -n 1 /proc/meminfo); RAM=(${MEM// / });
      MAX_JOBS=$(( ${RAM[1]} / 393216 )); echo Max jobs\:\ $MAX_JOBS;
      CORES=$(grep -c ^processor /proc/cpuinfo);
      [ $CORES -lt $MAX_JOBS ] && MAX_JOBS=$CORES; echo Real jobs\:\ $MAX_JOBS;
      ${CC} --version; ${CXX} --version;
      ./scripts/build.sh -j $MAX_JOBS;
      export CC=`which gcc-5`;
      export CXX=`which g++-5`;
      ${CC} --version; ${CXX} --version;
      ./scripts/build.sh -j $MAX_JOBS;
    else
      export CC=`which clang-3.8`;
      export CXX=`which clang++-3.8`;
      ${CC} --version ; ${CXX} --version;
      ./scripts/build.sh;
    fi
