
Import('check_env')

env = check_env.Clone()

env.Prepend(LIBS=File('#/galerautils/src/libgalerautils.a'))
env.Prepend(LIBS=File('#/galerautils/src/libgalerautils++.a'))
env.Prepend(LIBS=File('#/gcache/src/libgcache.a'))

gcache_tests = env.Program(target = 'gcache_tests', source = Glob('*.cpp'))

#                           source = Split('''
#                                 gcache_tests.cpp
#                           '''))

stamp="gcache_tests.passed"
env.Test(stamp, gcache_tests)
env.Alias("test", stamp)

