
env = DefaultEnvironment()

libwsdb_files = Split('''
                         certification.c
                         file.c
                         file_cache.c
                         hash.c
                         local.c
                         version_file.c
                         wsdb_xdr.c
                         conn.c
                         key_array.c
                         mempool.c
                         wsdb.c
                      ''')
env.SharedLibrary('wsdb', libwsdb_files)
env.StaticLibrary('wsdb', libwsdb_files)
