
Import('check_env')

env = check_env.Clone()

env.Append(LIBS=File('#/gcomm/src/libgcomm.a'))
env.Append(LIBS=File('#/galerautils/src/libgalerautils++.a'))
env.Append(LIBS=File('#/galerautils/src/libgalerautils.a'))

gcomm_check = env.Program(target = 'check_gcomm',
                          source = Split('''
                              check_gcomm.cpp
                              check_trace.cpp
                              check_types.cpp
                              check_util.cpp
                              check_gmcast.cpp
                              check_evs2.cpp
                              check_pc.cpp
                           '''))

env.Test("gcomm_check.passed", gcomm_check)


ssl_test = env.Program(target = 'ssl_test',
                       source = ['ssl_test.cpp'])
