
Import('check_env')

env = check_env.Clone()

env.Prepend(LIBS = Split('''
                            gcomm
                            galerautils++
                            galerautils
                         '''))

gcomm_check = env.Program(target = 'check_gcomm',
                          source = Split('''
                              check_gcomm.cpp
                              check_trace.cpp
                              check_types.cpp
                              check_util.cpp
                              check_gmcast.cpp
                              check_evs2.cpp
                              check_pc.cpp
                           '''))

# temporarily disabled env.Test("gcomm_check.passed", gcomm_check)
env.Alias("test", "gcomm_check.passed")
