
Import('check_env')

env = check_env.Clone()

env.Append(LIBS=File('#/galerautils/src/libgalerautils++.a'))
env.Append(LIBS=File('#/galerautils/src/libgalerautils.a'))

gu_tests = env.Program(target = 'gu_tests',
                       source = Split('''
                            gu_tests.c
                            gu_mem_test.c
                            gu_bswap_test.c
                            gu_time_test.c
                            gu_fifo_test.c
                            gu_uuid_test.c
                            gu_dbug_test.c
                            gu_lock_step_test.c
                            gu_str_test.c
                            gu_utils_test.c
                         '''))

env.Test("gu_tests.passed", gu_tests)
env.Alias("test", "gu_tests.passed")


gu_testspp = env.Program(target = 'gu_tests++',
                         source = Split('''
                              gu_tests++.cpp
                              gu_string_test.cpp
                              gu_uri_test.cpp
                              gu_net_test.cpp
                              gu_datetime_test.cpp
                           '''))

env.Test("gu_tests++.passed", gu_testspp)
env.Alias("test", "gu_tests++.passed")
