
env = DefaultEnvironment()

env.SharedLibrary('galerautils', Glob('*.c'))
env.StaticLibrary('galerautils', Glob('*.c'))
env.SharedLibrary('galerautils++', Glob('*.cpp'))
env.StaticLibrary('galerautils++', Glob('*.cpp'))

