
gcache_env = DefaultEnvironment().Clone()

gcache_sources = Split ('''
        gcache_fd.cpp
        gcache_mmap.cpp
        GCache_seqno.cpp
        gcache_params.cpp
        gcache_page.cpp
        gcache_page_store.cpp
        gcache_rb_store.cpp
        GCache_memops.cpp
        GCache.cpp
''')

gcache_env.SharedLibrary('gcache', gcache_sources)
gcache_env.StaticLibrary('gcache', gcache_sources)

test_env = gcache_env.Clone()
test_env.Append(LIBS=File('libgcache.a'))
test_env.Append(LIBS=File('#/galerautils/src/libgalerautils++.a'))
test_env.Append(LIBS=File('#/galerautils/src/libgalerautils.a'))

test_env.Program(source='test.cpp')

