
env = DefaultEnvironment()

env.Replace(CXXFLAGS = '-DGALERA_LOG_H_ENABLE_CXX -Wno-long-long -Wno-deprecated -Weffc++ -ansi')

env.SharedLibrary('mmgalera', [
        'galera_info.c',
        'galera_job_queue.c',
        'galera_options.c',
        'galera_state.c',
        'galera_status.c',
        'mm_galera_refact.cpp',
        'write_set.cpp',
        'wsdb.cpp',
        'certification.cpp',
        'galera_wsdb.cpp',
        'galera_certification.cpp'
])

env.StaticLibrary('mmgalera', [
        'galera_info.c',
        'galera_job_queue.c',
        'galera_options.c',
        'galera_state.c',
        'galera_status.c',
        'mm_galera.c',
        'write_set.cpp',
        'wsdb.cpp',
        'certification.cpp',
        'galera_wsdb.cpp',
        'galera_certification.cpp'
])
