
Import('check_env')

env = check_env.Clone()
env.Append(LIBS = ['galera++',
                   'galerautils++',
                   'galerautils',
                   'pthread'])

env.Program(target='galera_check',
            source=Split('''
                            galera_check.cpp
                            write_set_check.cpp
                            service_thd_check.cpp
                         ''')
            )
