
Import('check_env')

env = check_env.Clone()
env.Append(LIBS = ['galera++',
                   'galerautils++',
                   'galerautils',
                   'pthread',
                   'rt'])

galera_check = env.Program(target='galera_check',
                           source=Split('''
                               galera_check.cpp
                               write_set_check.cpp
                               trx_handle_check.cpp
                               service_thd_check.cpp
                           '''))

stamp = "galera_check.passed"
env.Test(stamp, galera_check)
env.Alias("test", stamp)
